import { useEffect, useState } from "react";
import axios from "../../../instance/Axios";
import Swal from "sweetalert2";

export default function AdminPinGenerator() {
  const [currentPin, setCurrentPin] = useState({
    pin: "",
    generatedBy: "",
    email: "",
    createdAt: "",
  });

  const [pinInput, setPinInput] = useState("");
  const [confirmPinInput, setConfirmPinInput] = useState("");
  const [revealCurrent, setRevealCurrent] = useState(false);
  const [loading, setLoading] = useState(true);

  const pinPattern = /^[A-Z]{3}\d{3}$/;

  const handlePinChange = (e) => {
    setPinInput(e.target.value.toUpperCase().slice(0, 6));
  };

  const handleConfirmPinChange = (e) => {
    setConfirmPinInput(e.target.value.toUpperCase().slice(0, 6));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!pinPattern.test(pinInput) || !pinPattern.test(confirmPinInput)) {
      Swal.fire({
        icon: "warning",
        title: "Invalid Format",
        text: "PIN must be 3 letters followed by 3 digits (e.g., ABC123).",
      });
      return;
    }

    if (pinInput !== confirmPinInput) {
      Swal.fire({
        icon: "error",
        title: "Mismatch",
        text: "PIN and confirmation PIN do not match.",
      });
      return;
    }

    if (pinInput === currentPin.pin) {
      Swal.fire({
        icon: "info",
        title: "Duplicate PIN",
        text: "This PIN is the same as the current PIN. Please choose a new one.",
      });
      return;
    }

    try {
      Swal.fire({
        title: "Creating PIN...",
        allowOutsideClick: false,
        didOpen: () => {
          Swal.showLoading();
        },
      });

      const response = await axios.post("/auth/create/pin", { pin: pinInput });
      const newPin = response.data.data; // expects { code, staff, createdAt }

      setCurrentPin({
        pin: newPin.code.toUpperCase(),
        generatedBy: newPin.staff?.name || "Unknown",
        email: newPin.staff?.email || "",
        createdAt: newPin.createdAt,
      });

      setPinInput("");
      setConfirmPinInput("");
      setRevealCurrent(false);

      Swal.fire({
        icon: "success",
        title: "PIN Created",
        text: `New PIN ${newPin.code.toUpperCase()} was successfully created.`,
      });
    } catch (error) {
      Swal.fire({
        icon: "error",
        title: "Error",
        text: error?.response?.data?.message || "Failed to create PIN. Please try again.",
      });
    }
  };

  const getCurrentPin = async () => {
    try {
      setLoading(true);
      const response = await axios.get("/auth/pin");

      const existingPin = response.data.data.existing;
      setCurrentPin({
        pin: existingPin.code.toUpperCase(),
        generatedBy: existingPin.staff?.name || `Staff ID: ${existingPin.staffId}`,
        email: existingPin.staff?.email || "",
        createdAt: existingPin.createdAt,
      });
    } catch (error) {
      Swal.fire({
        icon: "error",
        title: "Error",
        text: "Failed to fetch current PIN. Please try again.",
      });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    getCurrentPin();
  }, []);

  // Format date nicely
  const formatDateTime = (dateString) => {
    if (!dateString) return "";
    return new Date(dateString).toLocaleString("en-GB", {
      day: "2-digit",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full">
        <p className="text-gray-600 animate-pulse">Loading current PIN...</p>
      </div>
    );
  }

  return (
    <div className="flex items-center justify-center p-6 bg-gray-50 h-full">
      <div className="bg-white rounded-lg shadow-md p-6 w-full max-w-2xl text-center">
        <h1 className="text-xl font-bold text-gray-800 mb-6 flex items-center justify-center gap-2">
          🔒 Admin PIN Creator
        </h1>

        {/* Current PIN */}
        <div className="bg-gray-100 rounded-lg p-4 text-left mb-6">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-gray-600 text-sm font-medium">Current PIN</p>
              <p className="text-gray-800 mt-1 font-bold text-2xl tracking-widest">
                {revealCurrent
                  ? currentPin.pin
                  : "•".repeat(currentPin.pin.length || 6)}
              </p>
              {currentPin.createdAt && (
                <p className="text-gray-500 text-xs mt-1">
                  Created at: {formatDateTime(currentPin.createdAt)}
                </p>
              )}
            </div>
            <div className="text-right">
              <p className="text-gray-500 text-sm">Generated by</p>
              <p className="text-gray-700 font-semibold">
                {currentPin.generatedBy}
              </p>
              {currentPin.email && (
                <p className="text-gray-500 text-xs">{currentPin.email}</p>
              )}
            </div>
          </div>
          <div className="mt-3 flex items-center gap-2">
            <button
              type="button"
              onClick={() => setRevealCurrent((r) => !r)}
              className="px-3 py-1 rounded-md bg-blue-100 text-blue-700 text-sm font-medium"
            >
              {revealCurrent ? "Hide" : "Reveal"}
            </button>
          </div>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="max-w-md mx-auto">
          <p className="text-gray-500 text-sm mb-3">
            PIN must be <strong>3 letters (A-Z) followed by 3 digits (0-9)</strong>{" "}
            e.g., ABC123
          </p>

          <label htmlFor="pin" className="block text-gray-700 mb-1">
            New PIN
          </label>
          <input
            type="text"
            id="pin"
            value={pinInput}
            onChange={handlePinChange}
            maxLength={6}
            className="w-full p-2 rounded-md border border-gray-300 mb-3 text-center focus:outline-none focus:ring-2 focus:ring-blue-400"
            placeholder="ABC123"
            required
          />

          <label htmlFor="confirmPin" className="block text-gray-700 mb-1">
            Confirm PIN
          </label>
          <input
            type="text"
            id="confirmPin"
            value={confirmPinInput}
            onChange={handleConfirmPinChange}
            maxLength={6}
            className="w-full p-2 rounded-md border border-gray-300 mb-3 text-center focus:outline-none focus:ring-2 focus:ring-blue-400"
            placeholder="ABC123"
            required
          />

          <button
            type="submit"
            disabled={
              !pinPattern.test(pinInput) ||
              pinInput !== confirmPinInput ||
              pinInput === currentPin.pin
            }
            className={`w-full p-2 rounded-md font-semibold transition-colors ${
              pinPattern.test(pinInput) &&
              pinInput === confirmPinInput &&
              pinInput !== currentPin.pin
                ? "bg-blue-500 text-white hover:bg-blue-600"
                : "bg-gray-300 text-gray-500 cursor-not-allowed"
            }`}
          >
            Create Admin PIN
          </button>
        </form>
      </div>
    </div>
  );
}
